services:
  kahoot-server:
    build: ./server
    command: uvicorn kahoot_server:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./server:/app
    ports:
      - "8080:8080"
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    depends_on:
      - kahoot-db

  kahoot-db:
    build: ./database
    command: uvicorn main_rest_api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./database:/app
    ports:
      - "8000:8000"
    working_dir: /app
    environment:
      - PYTHONPATH=/app

  kahoot-client:
    build: ./client
    command: npm run dev
    volumes:
      - ./client:/app
    ports:
      - "5173:5173"
    working_dir: /app
    stdin_open: true
    tty: true
