# I got this from chatgpt i'll look through it later
services:
  server:
    build: ./server
    container_name: kahoot-server
    ports:
      - "8080:8080"
    networks:
      - kahoot-net
  
  client:
    build: ./client
    container_name: kahoot-client
    ports:
      - "80:5173"
    depends_on:
      - server
    networks:
      - kahoot-net

  postgres:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


networks:
  kahoot-net:
    driver: bridge