version: "3.9"

# I got this from chatgpt i'll look through it later
services:
  server:
    build: ./server
    container_name: kahoot-server
    ports:
      - "8080"
    networks:
      - kahoot-net
  
  client:
    build: ./client
    container_name: kahoot-client
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - kahoot-net

networks:
  kahoot-net:
    driver: bridge